# Generated by Django 6.0.7 on 2026-07-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickify', '0003_utmmedium_utmsource_clicklog_utm_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickReport',
            fields=[
            ],
            options={
                'verbose_name': 'Click Report',
                'verbose_name_plural': 'Click Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clickify.clicklog',),
        ),
    ]
